services:
  neo4j-final:
    image: neo4j:5-community
    container_name: ahd-neo4j-final
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    volumes:
      - neo4j_final_data:/data

volumes:
  neo4j_final_data:
